# Generated by Django 6.0.4 on 2026-04-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_tx_hash',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='onchain_project_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
